import unittest

from inference.rejection_forward_test import RejectionForwardTest
from inference.rejection_backward_test import RejectionBackwardTest
from inference.contraction_test import ContractionTest

from preparation.formula_qubit_preparation import PreparationTest
from preparation.inversion_test import InversionTest
from preparation.deutsch_josza import DeutschJoszaTest

unittest.main()